---
title: "conclusion"
author: "Manunpat"
date: "2022-12-11"
output: html_document
---

```{r,include=FALSE}
source(here::here("scripts/setup.R"))
```

# 9. Conclusion      

The results of sentiment analysis suggested that TED talks tend to present a positive sentiment, which may be intended to inspire and motivate audiences. On the other hand, we could observe that the results of sentiment analysis may not differentiate between different categories of documents or texts, so to some extent there is the lack of diversity in term of the videos' sentiment.  

Topic analysis was then used to cluster the TED videos and compare the results to the known categories provided by the TED website. The data visualization from the topic modeling study showed that the clusters generated by both Latent Semantic Analysis (LSA) and Latent Dirichlet Allocation (LDA) were closely aligned with the categories labeled by the TED website. Additionally, the performance of a supervised learning model that used the results of LSA as features was assessed, providing a more quantitative measure of the effectiveness of LSA in categorizing the texts.

Supervised learning techniques were applied to predict the category of TED videos using a random forest model. Four different sets of features were used for the prediction model: Latent Semantic Analysis (LSA) on Term Frequency (TF), LSA on Term Frequency-Inverse Document Frequency (TF-IDF), document embeddings, and a combination of LSA on TF-IDF and additional information such as the number of likes and views. The results showed that the last model had the highest accuracy, with an accuracy and all balanced accuracies of over 0.90 for all categories.

  
# 10. Further study and Limitation    

One of the limitations of the data used in our analysis is the difficulty of obtaining a large amount of transcript data due to limitations in time and computer capacity. Additionally, the structure of the TED website is not conducive to scraping text, which hinders the richness and diversity of the data. Furthermore, the distribution of additional features on the TED website, such as information about the speakers and viewer comments, is fragmented, limiting the value of these features in our analysis.

In addition, we can expand our research based on the available information. For example, we can analyze trends in TED talk releases and predict their release schedule, which can help investors understand TED's plans and the messages it intends to deliver to its audience. We can also analyze the variations in the wording of speeches given by the same speakers or on the same topics. Additionally, TED currently has nearly 400 options for categorizing videos, which may not be ideal for users trying to find a specific topic. Therefore, TED can improve the classification of videos by analyzing which categories viewers are more inclined to comment on in their feedback.     

# Reference   
TED, https://www.ted.com/