
```{r,include=FALSE}
source(here::here("scripts/setup.R"))
```

# Abstract

In this study, we investigate the use of machine learning and text mining techniques to classify and analyze TED talk videos based on their transcript data. We perform sentiment analysis to identify the opinions and feelings expressed by TED speakers about each talk topic, and use topic analysis to cluster the videos and compare them to the categories labeled by the TED website. We also apply text classification techniques to predict the topics of new videos using a random forest model. Our results show that TED talks tend to present a positive sentiment and that the clusters generated by Latent Semantic Analysis (LSA) and Latent Dirichlet Allocation (LDA) align closely with the known categories. The supervised learning model using a combination of LSA on Term Frequency-Inverse Document Frequency (TF-IDF) and additional information had the highest accuracy, with an overall accuracy of 0.90. Limitations and potential directions for future research are also discussed.

# 1. Introduction

There are several ways to learn and share knowledge today, one of the most popular being short video clips. We are interested in using both machine learning and text mining techniques to analyze the classification of videos from their transcript or subtitle data. Initially, we considered several streaming websites and video podcasts, such as YouTube, BBC Learning English, Apple podcasts, and TED talk. TED was ultimately chosen for this project because of the availability of data for our study and its wide range of videos in terms of topics, languages, and lengths. Furthermore, each TED video is labeled with a relevant category and includes a transcript.

The goal of this project is to first use sentiment analysis to identify opinions, judgments, or feelings expressed by TED speakers about each TED talk topic. Second, we will use topic analysis to cluster the videos and compare them to the categories labeled by the TED website. Finally, we will apply text classification techniques to predict the topics of new videos.

The rest of the project is organized as follows: Section 2 describes the data and web scraping, Section 3 presents tokenization, Section 4 presents exploratory data analysis, Section 5 presents sentiment analysis, Section 6 performs topic modeling analysis, Section 7 performs embedding analysis, and Section 8 performs supervised analysis. The main results of the study, as well as limitations and potential future research, are presented in Section 9.
